### ISSUE TITLE
docker 설정

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#112]
### ISSUE
* Group: `server`
* Type: `feature`
* Detail: 도커 빌드 및 배포 설정

### TODO
- [x] Express Dockerfile 생성
- [x] docker-compose 스크립트 생성
- [x] cluster mode 설정
- [x] Server README 편집

### DUE DATE
`2022.10.03`
