### ISSUE TITLE
메인페이지 목업 구현

### ISSUE THREAD

**Issue by Esoolgnah** [codestates/ScratchNow#121]
### ISSUE
* Group: `client`
* Type: `feature`
* Detail: 메인페이지 목업 구현

### TODO

- [x] 배너 컴포넌트 생성
- [x] 메뉴 선택 컴포넌트 생성
- [x] 게시물 컴포넌트 생성

### DUE DATE
`2022.12.17`
