### ISSUE TITLE
[Task] SR 기획

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#49]
### ISSUE
* Group: `client`, `server`, `sr`
* Type: `feature`
* Detail: 서비스 기획 설계 및 사용 스택 논의(프로젝트 시작 예정: 8월)

### TODO
- [ ] 서비스 기획 범위 설계
- [ ] 사용 스택 선정
- [ ] 개발 작업 로드맵 설정
