### ISSUE TITLE
[Task] Server 개발 환경 구축

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#51]
### ISSUE
* Group: `server`
* Type: 
* Detail: 사용 모듈 설치 및 서버 개발 환경 구축

### TODO
- [ ] Express 서버 구축
- [ ] 사용 예정 모듈 설치
- [ ] MVC 구조 설계

### Estimated time
`1h`

### Labels
* Estimated time: `E: 1h`
* Group : `server`
