### ISSUE TITLE
회원 계정 관련 API 개발(1차)

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#64]
### ISSUE
* Group: `server`
* Type: `feature`
* Detail: sign, userinfo 관련 API 개발

### TODO
- [x] sequelize 연결 확인
- [x] signController 기능 개발
- [x] userinfoController 기능 개발

### DUE DATE
`2022.08.26`
