### ISSUE TITLE
좋아요 관련 API 개발(1차)

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#73]
### ISSUE
* Group: `server`
* Type: `feature`
* Detail: 게시물에 대한 좋아요 API 개발

### TODO
- [x] Likes 테이블 soft delete 방식 사용 여부 재검토 후 필요 시 수정
- [x] 좋아요 추가 API
- [x] 좋아요 취소 API

### DUE DATE
`2022.09.04`
