### ISSUE TITLE
댓글 관련 API 개발(1차)

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#74]
### ISSUE
* Group: `server`
* Type: `feature`
* Detail: 댓글 기능 API 개발

### TODO
- [x] 댓글 작성 API
- [x] 댓글 수정 API
- [x] 댓글 삭제 API
- [x] 댓글 조회 API

### DUE DATE
`2022.09.06`
