### ISSUE TITLE
회원정보 관련 API 로직 개발

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#75]
### ISSUE
* Group: `server`
* Type: `feature`
* Detail: 회원정보 수정 API 세분화 및 구현, 회원정보 조회 API 추가

### TODO
- [x] 사용자가 항목별로 별도 저장 방식
- [x] 닉네임 중복 확인 후 팝업창으로 저장하는 시나리오
- [x] 프로필 이미지 제거

### DUE DATE
`2022.09.07`
