### ISSUE TITLE
API 응답 데이터 점검 및 수정

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#89]
### ISSUE
* Group: `server`
* Type: `feature`, `refactor`
* Detail: 모든 API 통신에 대한 응답 데이터 점검 및 필요 시 수정

### TODO
- [x] API 작동 테스트
- [x] 유저 게시물 피드에서 유저정보 응답 데이터 제외
- [x] 인기순 전체피드에서 정렬 두번째 기준 지정

### DUE DATE
`2022.09.00`
