### ISSUE TITLE
댓글 API 수정

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#93]
### ISSUE
* Group: `server`
* Type: `bug`,  `refactor`
* Detail: 댓글 API 응답 데이터 점검 및 수정

### TODO
- [x] getComments 응답 데이터에서 오리지널 댓글만 1차 필터링 시도
- [x] HTTP 상태코드 수정
- [x] response body 객체 키명 통일
- [x] 추가 에러 발견사항 수정

### DUE DATE
`2022.09.16`
