### ISSUE TITLE
회원가입 관련 API 수정

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#95]
### ISSUE
* Group: `server`
* Type: `feature`, `refactor`
* Detail: 인증 시 페이로드 및 소셜로그인 로직 리팩토링

### TODO
- [x] 인증 페이로드에서 비밀번호 제외
- [x] Google OAuth DB 저장 값 수정
- [x] OAuth 코드 리펙토링
- [x] 사용자 테이블에 소셜로그인 구분 컬럼 추가

### DUE DATE
`2022.09.17`
