### ISSUE TITLE
DB 옵션 수정

### ISSUE THREAD

**Issue by alsrlqor1007** [codestates/ScratchNow#97]
### ISSUE
* Group: `server`
* Type: `feature`,  `refactor`
* Detail: Sequelize, MySQL 점검 및 수정

### TODO
- [x] Sequelize Typescript 문서 참고
- [x] 테이블명 단수로 변경
- [ ] onDelete, cascade 같은 DB 옵션 재설정

### DUE DATE
`2022.09.18`
